name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

branches:
  - develop

categories:
  - title: ':rocket: Experimental Features'
    labels:
      - 'changelog:feature'

  - title: ':pill: Bug Fixes'
    labels:
      - 'changelog:fix'

  - title: ':wrench: Maintenance'
    labels:
      - 'changelog:chore'

exclude-labels:
  - 'changelog:none'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## Changes

  $CHANGES
