# .github/release.yml

changelog:
  exclude:
    labels:
      - 'changelog:none'
  categories:
      - title: ':rocket: Experimental Features'
        labels:
          - 'changelog:feature'
      - title: ':pill: Bug Fixes'
        labels:
          - 'changelog:fix'
      - title: ':wrench: Maintenance'
        labels:
          - 'changelog:chore'

