#!/bin/sh
if [ $# -lt 1 ]; then
  echo "usage: cgnsupdate inputCGNSfile [outputCGNSfile]"
  exit 1
fi
dir=`dirname $0`
if ! [ -x $dir/cgnscheck ]; then
  echo "cgnscheck does not exist in $dir"
  exit 1
fi
$dir/cgnscheck -U $1 $2
