history_header_map = {'ADJOINT_DISP_X': {'DESCRIPTION': '',
                    'GROUP': 'RESIDUALS',
                    'HEADER': 'Res[Ux_adj]',
                    'TYPE': 'DEFAULT'},
 'ADJOINT_DISP_Y': {'DESCRIPTION': '',
                    'GROUP': 'RESIDUALS',
                    'HEADER': 'Res[Uy_adj]',
                    'TYPE': 'DEFAULT'},
 'ADJOINT_DISP_Z': {'DESCRIPTION': '',
                    'GROUP': 'RESIDUALS',
                    'HEADER': 'Res[Uz_adj]',
                    'TYPE': 'DEFAULT'},
 'AEROCDRAG': {'DESCRIPTION': 'Aero CD drag',
               'GROUP': 'ENGINE_OUTPUT',
               'HEADER': 'AeroCDrag',
               'TYPE': 'COEFFICIENT'},
 'AOA': {'DESCRIPTION': 'Angle of attack',
         'GROUP': 'AOA',
         'HEADER': 'AoA',
         'TYPE': 'DEFAULT'},
 'AVG_DENSITY': {'DESCRIPTION': 'Total average density on all markers set in '
                                'MARKER_ANALYZE',
                 'GROUP': 'FLOW_COEFF',
                 'HEADER': 'Avg_Density',
                 'TYPE': 'COEFFICIENT'},
 'AVG_ENTHALPY': {'DESCRIPTION': 'Total average enthalpy on all markers set in '
                                 'MARKER_ANALYZE',
                  'GROUP': 'FLOW_COEFF',
                  'HEADER': 'Avg_Enthalpy',
                  'TYPE': 'COEFFICIENT'},
 'AVG_MACH': {'DESCRIPTION': 'Total average mach number on all markers set in '
                             'MARKER_ANALYZE',
              'GROUP': 'FLOW_COEFF',
              'HEADER': 'Avg_Mach',
              'TYPE': 'COEFFICIENT'},
 'AVG_MASSFLOW': {'DESCRIPTION': 'Total average mass flow on all markers set '
                                 'in MARKER_ANALYZE',
                  'GROUP': 'FLOW_COEFF',
                  'HEADER': 'Avg_Massflow',
                  'TYPE': 'COEFFICIENT'},
 'AVG_NORMALVEL': {'DESCRIPTION': 'Total average normal velocity on all '
                                  'markers set in MARKER_ANALYZE',
                   'GROUP': 'FLOW_COEFF',
                   'HEADER': 'Avg_NormalVel',
                   'TYPE': 'COEFFICIENT'},
 'AVG_PRESS': {'DESCRIPTION': 'Total average pressure on all markers set in '
                              'MARKER_ANALYZE',
               'GROUP': 'FLOW_COEFF',
               'HEADER': 'Avg_Press',
               'TYPE': 'COEFFICIENT'},
 'AVG_TEMP': {'DESCRIPTION': 'Total average temperature on all markers set in '
                             'MARKER_ANALYZE',
              'GROUP': 'FLOW_COEFF',
              'HEADER': 'Avg_Temp',
              'TYPE': 'COEFFICIENT'},
 'AVG_TEMPERATURE': {'DESCRIPTION': 'Total average temperature on all surfaces '
                                    'defined in MARKER_MONITORING',
                     'GROUP': 'HEAT',
                     'HEADER': 'AvgTemp',
                     'TYPE': 'COEFFICIENT'},
 'AVG_TOTALPRESS': {'DESCRIPTION': 'Total average total pressure on all '
                                   'markers set in MARKER_ANALYZE',
                    'GROUP': 'FLOW_COEFF',
                    'HEADER': 'Avg_TotalPress',
                    'TYPE': 'COEFFICIENT'},
 'AVG_TOTALTEMP': {'DESCRIPTION': 'Total average total temperature all markers '
                                  'set in MARKER_ANALYZE',
                   'GROUP': 'FLOW_COEFF',
                   'HEADER': 'Avg_TotalTemp',
                   'TYPE': 'COEFFICIENT'},
 'BGS_ADJ_DENSITY': {'DESCRIPTION': 'BGS residual of the adjoint density.',
                     'GROUP': 'BGS_RES',
                     'HEADER': 'bgs[A_Rho]',
                     'TYPE': 'RESIDUAL'},
 'BGS_ADJ_DISSIPATION': {'DESCRIPTION': 'BGS residual of the adjoint '
                                        'dissipation.',
                         'GROUP': 'BGS_RES',
                         'HEADER': 'bgs[A_w]',
                         'TYPE': 'RESIDUAL'},
 'BGS_ADJ_ENERGY': {'DESCRIPTION': 'BGS residual of the adjoint energy.',
                    'GROUP': 'BGS_RES',
                    'HEADER': 'bgs[A_E]',
                    'TYPE': 'RESIDUAL'},
 'BGS_ADJ_HEAT': {'DESCRIPTION': 'BGS residual of the adjoint temperature.',
                  'GROUP': 'BGS_RES',
                  'HEADER': 'bgs[A_T]',
                  'TYPE': 'RESIDUAL'},
 'BGS_ADJ_MOMENTUM-X': {'DESCRIPTION': 'BGS residual of the adjoint momentum '
                                       'x-component',
                        'GROUP': 'BGS_RES',
                        'HEADER': 'bgs[A_RhoU]',
                        'TYPE': 'RESIDUAL'},
 'BGS_ADJ_MOMENTUM-Y': {'DESCRIPTION': 'BGS residual of the adjoint momentum '
                                       'y-component',
                        'GROUP': 'BGS_RES',
                        'HEADER': 'bgs[A_RhoV]',
                        'TYPE': 'RESIDUAL'},
 'BGS_ADJ_MOMENTUM-Z': {'DESCRIPTION': 'BGS residual of the adjoint momentum '
                                       'z-component',
                        'GROUP': 'BGS_RES',
                        'HEADER': 'bgs[A_RhoW]',
                        'TYPE': 'RESIDUAL'},
 'BGS_ADJ_NU_TILDE': {'DESCRIPTION': 'BGS residual of the adjoint nu tilde.',
                      'GROUP': 'BGS_RES',
                      'HEADER': 'bgs[A_nu]',
                      'TYPE': 'RESIDUAL'},
 'BGS_ADJ_PRESSURE': {'DESCRIPTION': 'BGS residual of the adjoint Pressure.',
                      'GROUP': 'BGS_RES',
                      'HEADER': 'bgs[A_Rho]',
                      'TYPE': 'RESIDUAL'},
 'BGS_ADJ_TKE': {'DESCRIPTION': 'BGS residual of the adjoint kinetic energy.',
                 'GROUP': 'BGS_RES',
                 'HEADER': 'bgs[A_k]',
                 'TYPE': 'RESIDUAL'},
 'BGS_ADJ_VELOCITY-X': {'DESCRIPTION': 'BGS residual of the adjoint Velocity '
                                       'x-component',
                        'GROUP': 'BGS_RES',
                        'HEADER': 'bsg[A_RhoU]',
                        'TYPE': 'RESIDUAL'},
 'BGS_ADJ_VELOCITY-Y': {'DESCRIPTION': 'BGS residual of the adjoint Velocity '
                                       'y-component',
                        'GROUP': 'BGS_RES',
                        'HEADER': 'bgs[A_RhoV]',
                        'TYPE': 'RESIDUAL'},
 'BGS_ADJ_VELOCITY-Z': {'DESCRIPTION': 'BGS residual of the adjoint Velocity '
                                       'z-component',
                        'GROUP': 'BGS_RES',
                        'HEADER': 'bgs[A_RhoW]',
                        'TYPE': 'RESIDUAL'},
 'BGS_DENSITY': {'DESCRIPTION': 'BGS residual of the density.',
                 'GROUP': 'BGS_RES',
                 'HEADER': 'bgs[Rho]',
                 'TYPE': 'RESIDUAL'},
 'BGS_DISP_X': {'DESCRIPTION': '',
                'GROUP': 'BGS_RES',
                'HEADER': 'bgs[DispX]',
                'TYPE': 'RESIDUAL'},
 'BGS_DISP_Y': {'DESCRIPTION': '',
                'GROUP': 'BGS_RES',
                'HEADER': 'bgs[DispY]',
                'TYPE': 'RESIDUAL'},
 'BGS_DISP_Z': {'DESCRIPTION': '',
                'GROUP': 'BGS_RES',
                'HEADER': 'bgs[DispZ]',
                'TYPE': 'RESIDUAL'},
 'BGS_DISSIPATION': {'DESCRIPTION': 'BGS residual of dissipation (SST model).',
                     'GROUP': 'BGS_RES',
                     'HEADER': 'bgs[w]',
                     'TYPE': 'RESIDUAL'},
 'BGS_ENERGY': {'DESCRIPTION': 'BGS residual of the energy.',
                'GROUP': 'BGS_RES',
                'HEADER': 'bgs[RhoE]',
                'TYPE': 'RESIDUAL'},
 'BGS_MOMENTUM-X': {'DESCRIPTION': 'BGS residual of the momentum x-component.',
                    'GROUP': 'BGS_RES',
                    'HEADER': 'bgs[RhoU]',
                    'TYPE': 'RESIDUAL'},
 'BGS_MOMENTUM-Y': {'DESCRIPTION': 'BGS residual of the momentum y-component.',
                    'GROUP': 'BGS_RES',
                    'HEADER': 'bgs[RhoV]',
                    'TYPE': 'RESIDUAL'},
 'BGS_NU_TILDE': {'DESCRIPTION': 'BGS residual of nu tilde (SA model).',
                  'GROUP': 'BGS_RES',
                  'HEADER': 'bgs[nu]',
                  'TYPE': 'RESIDUAL'},
 'BGS_PRESSURE': {'DESCRIPTION': 'BGS residual of the pressure.',
                  'GROUP': 'BGS_RES',
                  'HEADER': 'bgs[P]',
                  'TYPE': 'RESIDUAL'},
 'BGS_TEMPERATURE': {'DESCRIPTION': 'Block-Gauss seidel residual of the '
                                    'temperature',
                     'GROUP': 'BGS_RES',
                     'HEADER': 'bgs[T]',
                     'TYPE': 'RESIDUAL'},
 'BGS_TKE': {'DESCRIPTION': 'BGS residual of kinetic energy (SST model).',
             'GROUP': 'BGS_RES',
             'HEADER': 'bgs[k]',
             'TYPE': 'RESIDUAL'},
 'BGS_VELOCITY-X': {'DESCRIPTION': 'BGS residual of the velocity x-component.',
                    'GROUP': 'BGS_RES',
                    'HEADER': 'bgs[U]',
                    'TYPE': 'RESIDUAL'},
 'BGS_VELOCITY-Y': {'DESCRIPTION': 'BGS residual of the velocity y-component.',
                    'GROUP': 'BGS_RES',
                    'HEADER': 'bgs[V]',
                    'TYPE': 'RESIDUAL'},
 'BGS_VELOCITY-Z': {'DESCRIPTION': 'BGS residual of the velocity z-component.',
                    'GROUP': 'BGS_RES',
                    'HEADER': 'bgs[W]',
                    'TYPE': 'RESIDUAL'},
 'CFL_NUMBER': {'DESCRIPTION': 'Current value of the CFL number',
                'GROUP': 'CFL_NUMBER',
                'HEADER': 'CFL number',
                'TYPE': 'DEFAULT'},
 'CIRCUMFERENTIAL_DISTORTION': {'DESCRIPTION': 'Circumferential distortion',
                                'GROUP': 'ENGINE_OUTPUT',
                                'HEADER': 'Circumferential_Distortion',
                                'TYPE': 'COEFFICIENT'},
 'COMBO': {'DESCRIPTION': 'Combined obj. function value.',
           'GROUP': 'COMBO',
           'HEADER': 'ComboObj',
           'TYPE': 'COEFFICIENT'},
 'CP_DIFF': {'DESCRIPTION': 'Cp difference for inverse design',
             'GROUP': 'CP_DIFF',
             'HEADER': 'Cp_Diff',
             'TYPE': 'DEFAULT'},
 'CQ': {'DESCRIPTION': 'CQ',
        'GROUP': 'ROTATING_FRAME',
        'HEADER': 'CQ',
        'TYPE': 'COEFFICIENT'},
 'CT': {'DESCRIPTION': 'CT',
        'GROUP': 'ROTATING_FRAME',
        'HEADER': 'CT',
        'TYPE': 'COEFFICIENT'},
 'DEFORM_ITER': {'DESCRIPTION': 'Linear solver iterations for the mesh '
                                'deformation',
                 'GROUP': 'DEFORM',
                 'HEADER': 'DeformIter',
                 'TYPE': 'DEFAULT'},
 'DEFORM_MAX_VOLUME': {'DESCRIPTION': 'Maximum volume in the mesh',
                       'GROUP': 'DEFORM',
                       'HEADER': 'MaxVolume',
                       'TYPE': 'DEFAULT'},
 'DEFORM_MIN_VOLUME': {'DESCRIPTION': 'Minimum volume in the mesh',
                       'GROUP': 'DEFORM',
                       'HEADER': 'MinVolume',
                       'TYPE': 'DEFAULT'},
 'DEFORM_RESIDUAL': {'DESCRIPTION': 'Residual of the linear solver for the '
                                    'mesh deformation',
                     'GROUP': 'DEFORM',
                     'HEADER': 'DeformRes',
                     'TYPE': 'DEFAULT'},
 'DRAG': {'DESCRIPTION': 'Total drag coefficient on all surfaces set with '
                         'MARKER_MONITORING',
          'GROUP': 'AERO_COEFF',
          'HEADER': 'CD',
          'TYPE': 'COEFFICIENT'},
 'D_AEROCDRAG': {'DESCRIPTION': 'Derivative value',
                 'GROUP': 'D_ENGINE_OUTPUT',
                 'HEADER': 'd[AeroCDrag]',
                 'TYPE': 'D_COEFFICIENT'},
 'D_AVG_DENSITY': {'DESCRIPTION': 'Derivative value',
                   'GROUP': 'D_FLOW_COEFF',
                   'HEADER': 'd[Avg_Density]',
                   'TYPE': 'D_COEFFICIENT'},
 'D_AVG_ENTHALPY': {'DESCRIPTION': 'Derivative value',
                    'GROUP': 'D_FLOW_COEFF',
                    'HEADER': 'd[Avg_Enthalpy]',
                    'TYPE': 'D_COEFFICIENT'},
 'D_AVG_MACH': {'DESCRIPTION': 'Derivative value',
                'GROUP': 'D_FLOW_COEFF',
                'HEADER': 'd[Avg_Mach]',
                'TYPE': 'D_COEFFICIENT'},
 'D_AVG_MASSFLOW': {'DESCRIPTION': 'Derivative value',
                    'GROUP': 'D_FLOW_COEFF',
                    'HEADER': 'd[Avg_Massflow]',
                    'TYPE': 'D_COEFFICIENT'},
 'D_AVG_NORMALVEL': {'DESCRIPTION': 'Derivative value',
                     'GROUP': 'D_FLOW_COEFF',
                     'HEADER': 'd[Avg_NormalVel]',
                     'TYPE': 'D_COEFFICIENT'},
 'D_AVG_PRESS': {'DESCRIPTION': 'Derivative value',
                 'GROUP': 'D_FLOW_COEFF',
                 'HEADER': 'd[Avg_Press]',
                 'TYPE': 'D_COEFFICIENT'},
 'D_AVG_TEMP': {'DESCRIPTION': 'Derivative value',
                'GROUP': 'D_FLOW_COEFF',
                'HEADER': 'd[Avg_Temp]',
                'TYPE': 'D_COEFFICIENT'},
 'D_AVG_TEMPERATURE': {'DESCRIPTION': 'Derivative value',
                       'GROUP': 'D_HEAT',
                       'HEADER': 'd[AvgTemp]',
                       'TYPE': 'D_COEFFICIENT'},
 'D_AVG_TOTALPRESS': {'DESCRIPTION': 'Derivative value',
                      'GROUP': 'D_FLOW_COEFF',
                      'HEADER': 'd[Avg_TotalPress]',
                      'TYPE': 'D_COEFFICIENT'},
 'D_AVG_TOTALTEMP': {'DESCRIPTION': 'Derivative value',
                     'GROUP': 'D_FLOW_COEFF',
                     'HEADER': 'd[Avg_TotalTemp]',
                     'TYPE': 'D_COEFFICIENT'},
 'D_CIRCUMFERENTIAL_DISTORTION': {'DESCRIPTION': 'Derivative value',
                                  'GROUP': 'D_ENGINE_OUTPUT',
                                  'HEADER': 'd[Circumferential_Distortion]',
                                  'TYPE': 'D_COEFFICIENT'},
 'D_COMBO': {'DESCRIPTION': 'Derivative value',
             'GROUP': 'D_COMBO',
             'HEADER': 'd[ComboObj]',
             'TYPE': 'D_COEFFICIENT'},
 'D_CQ': {'DESCRIPTION': 'Derivative value',
          'GROUP': 'D_ROTATING_FRAME',
          'HEADER': 'd[CQ]',
          'TYPE': 'D_COEFFICIENT'},
 'D_CT': {'DESCRIPTION': 'Derivative value',
          'GROUP': 'D_ROTATING_FRAME',
          'HEADER': 'd[CT]',
          'TYPE': 'D_COEFFICIENT'},
 'D_DRAG': {'DESCRIPTION': 'Derivative value',
            'GROUP': 'D_AERO_COEFF',
            'HEADER': 'd[CD]',
            'TYPE': 'D_COEFFICIENT'},
 'D_EFFICIENCY': {'DESCRIPTION': 'Derivative value',
                  'GROUP': 'D_AERO_COEFF',
                  'HEADER': 'd[CEff]',
                  'TYPE': 'D_COEFFICIENT'},
 'D_EQUIV_AREA': {'DESCRIPTION': 'Derivative value',
                  'GROUP': 'D_EQUIVALENT_AREA',
                  'HEADER': 'd[CEquiv_Area]',
                  'TYPE': 'D_COEFFICIENT'},
 'D_FORCE_X': {'DESCRIPTION': 'Derivative value',
               'GROUP': 'D_AERO_COEFF',
               'HEADER': 'd[CFx]',
               'TYPE': 'D_COEFFICIENT'},
 'D_FORCE_Y': {'DESCRIPTION': 'Derivative value',
               'GROUP': 'D_AERO_COEFF',
               'HEADER': 'd[CFy]',
               'TYPE': 'D_COEFFICIENT'},
 'D_FORCE_Z': {'DESCRIPTION': 'Derivative value',
               'GROUP': 'D_AERO_COEFF',
               'HEADER': 'd[CFz]',
               'TYPE': 'D_COEFFICIENT'},
 'D_HEATFLUX': {'DESCRIPTION': 'Derivative value',
                'GROUP': 'D_HEAT',
                'HEADER': 'd[HF]',
                'TYPE': 'D_COEFFICIENT'},
 'D_HEATFLUX_MAX': {'DESCRIPTION': 'Derivative value',
                    'GROUP': 'D_HEAT',
                    'HEADER': 'd[MaxHF]',
                    'TYPE': 'D_COEFFICIENT'},
 'D_LIFT': {'DESCRIPTION': 'Derivative value',
            'GROUP': 'D_AERO_COEFF',
            'HEADER': 'd[CL]',
            'TYPE': 'D_COEFFICIENT'},
 'D_MERIT': {'DESCRIPTION': 'Derivative value',
             'GROUP': 'D_ROTATING_FRAME',
             'HEADER': 'd[CMerit]',
             'TYPE': 'D_COEFFICIENT'},
 'D_MOMENTUM_DISTORTION': {'DESCRIPTION': 'Derivative value',
                           'GROUP': 'D_FLOW_COEFF',
                           'HEADER': 'd[Momentum_Distortion]',
                           'TYPE': 'D_COEFFICIENT'},
 'D_MOMENT_X': {'DESCRIPTION': 'Derivative value',
                'GROUP': 'D_AERO_COEFF',
                'HEADER': 'd[CMx]',
                'TYPE': 'D_COEFFICIENT'},
 'D_MOMENT_Y': {'DESCRIPTION': 'Derivative value',
                'GROUP': 'D_AERO_COEFF',
                'HEADER': 'd[CMy]',
                'TYPE': 'D_COEFFICIENT'},
 'D_MOMENT_Z': {'DESCRIPTION': 'Derivative value',
                'GROUP': 'D_AERO_COEFF',
                'HEADER': 'd[CMz]',
                'TYPE': 'D_COEFFICIENT'},
 'D_NEARFIELD_OF': {'DESCRIPTION': 'Derivative value',
                    'GROUP': 'D_EQUIVALENT_AREA',
                    'HEADER': 'd[CNearFieldOF]',
                    'TYPE': 'D_COEFFICIENT'},
 'D_PRESSURE_DROP': {'DESCRIPTION': 'Derivative value',
                     'GROUP': 'D_FLOW_COEFF',
                     'HEADER': 'd[Pressure_Drop]',
                     'TYPE': 'D_COEFFICIENT'},
 'D_RADIAL_DISTORTION': {'DESCRIPTION': 'Derivative value',
                         'GROUP': 'D_ENGINE_OUTPUT',
                         'HEADER': 'd[Radial_Distortion]',
                         'TYPE': 'D_COEFFICIENT'},
 'D_SECONDARY_OVER_UNIFORMITY': {'DESCRIPTION': 'Derivative value',
                                 'GROUP': 'D_FLOW_COEFF',
                                 'HEADER': 'd[Secondary_Over_Uniformity]',
                                 'TYPE': 'D_COEFFICIENT'},
 'D_SECONDARY_STRENGTH': {'DESCRIPTION': 'Derivative value',
                          'GROUP': 'D_FLOW_COEFF',
                          'HEADER': 'd[Secondary_Strength]',
                          'TYPE': 'D_COEFFICIENT'},
 'D_SENS_AOA': {'DESCRIPTION': 'Derivative value',
                'GROUP': 'D_SENSITIVITY',
                'HEADER': 'd[Sens_AoA]',
                'TYPE': 'D_COEFFICIENT'},
 'D_SENS_GEO': {'DESCRIPTION': 'Derivative value',
                'GROUP': 'D_SENSITIVITY',
                'HEADER': 'd[Sens_Geo]',
                'TYPE': 'D_COEFFICIENT'},
 'D_SENS_MACH': {'DESCRIPTION': 'Derivative value',
                 'GROUP': 'D_SENSITIVITY',
                 'HEADER': 'd[Sens_Mach]',
                 'TYPE': 'D_COEFFICIENT'},
 'D_SENS_PRESS': {'DESCRIPTION': 'Derivative value',
                  'GROUP': 'D_SENSITIVITY',
                  'HEADER': 'd[Sens_Press]',
                  'TYPE': 'D_COEFFICIENT'},
 'D_SENS_PRESS_OUT': {'DESCRIPTION': 'Derivative value',
                      'GROUP': 'D_SENSITIVITY',
                      'HEADER': 'd[Sens_Pout]',
                      'TYPE': 'D_COEFFICIENT'},
 'D_SENS_TEMP': {'DESCRIPTION': 'Derivative value',
                 'GROUP': 'D_SENSITIVITY',
                 'HEADER': 'd[Sens_Temp]',
                 'TYPE': 'D_COEFFICIENT'},
 'D_SENS_VEL_IN': {'DESCRIPTION': 'Derivative value',
                   'GROUP': 'D_SENSITIVITY',
                   'HEADER': 'd[Sens_Vin]',
                   'TYPE': 'D_COEFFICIENT'},
 'D_SIDEFORCE': {'DESCRIPTION': 'Derivative value',
                 'GROUP': 'D_AERO_COEFF',
                 'HEADER': 'd[CSF]',
                 'TYPE': 'D_COEFFICIENT'},
 'D_SOLIDCDRAG': {'DESCRIPTION': 'Derivative value',
                  'GROUP': 'D_ENGINE_OUTPUT',
                  'HEADER': 'd[SolidCDrag]',
                  'TYPE': 'D_COEFFICIENT'},
 'D_TEMPERATURE': {'DESCRIPTION': 'Derivative value',
                   'GROUP': 'D_HEAT',
                   'HEADER': 'd[Temp]',
                   'TYPE': 'D_COEFFICIENT'},
 'D_UNIFORMITY': {'DESCRIPTION': 'Derivative value',
                  'GROUP': 'D_FLOW_COEFF',
                  'HEADER': 'd[Uniformity]',
                  'TYPE': 'D_COEFFICIENT'},
 'EFFICIENCY': {'DESCRIPTION': 'Total lift-to-drag ratio on all surfaces set '
                               'with MARKER_MONITORING',
                'GROUP': 'AERO_COEFF',
                'HEADER': 'CEff',
                'TYPE': 'COEFFICIENT'},
 'EQUIV_AREA': {'DESCRIPTION': 'Equivalent area',
                'GROUP': 'EQUIVALENT_AREA',
                'HEADER': 'CEquiv_Area',
                'TYPE': 'COEFFICIENT'},
 'FORCE_X': {'DESCRIPTION': 'Total force x-component on all surfaces set with '
                            'MARKER_MONITORING',
             'GROUP': 'AERO_COEFF',
             'HEADER': 'CFx',
             'TYPE': 'COEFFICIENT'},
 'FORCE_Y': {'DESCRIPTION': 'Total force y-component on all surfaces set with '
                            'MARKER_MONITORING',
             'GROUP': 'AERO_COEFF',
             'HEADER': 'CFy',
             'TYPE': 'COEFFICIENT'},
 'FORCE_Z': {'DESCRIPTION': 'Total force z-component on all surfaces set with '
                            'MARKER_MONITORING',
             'GROUP': 'AERO_COEFF',
             'HEADER': 'CFz',
             'TYPE': 'COEFFICIENT'},
 'HEATFLUX': {'DESCRIPTION': 'Total heatflux on all surfaces defined in '
                             'MARKER_MONITORING',
              'GROUP': 'HEAT',
              'HEADER': 'HF',
              'TYPE': 'COEFFICIENT'},
 'HEATFLUX_MAX': {'DESCRIPTION': 'Total maximal heatflux on all surfaces '
                                 'defined in MARKER_MONITORING',
                  'GROUP': 'HEAT',
                  'HEADER': 'MaxHF',
                  'TYPE': 'COEFFICIENT'},
 'LIFT': {'DESCRIPTION': 'Total lift coefficient on all surfaces set with '
                         'MARKER_MONITORING',
          'GROUP': 'AERO_COEFF',
          'HEADER': 'CL',
          'TYPE': 'COEFFICIENT'},
 'LINSOL_ITER': {'DESCRIPTION': 'Number of iterations of the linear solver.',
                 'GROUP': 'LINSOL',
                 'HEADER': 'LinSolIter',
                 'TYPE': 'DEFAULT'},
 'LINSOL_RESIDUAL': {'DESCRIPTION': 'Residual of the linear solver.',
                     'GROUP': 'LINSOL',
                     'HEADER': 'LinSolRes',
                     'TYPE': 'DEFAULT'},
 'LOAD_INCREMENT': {'DESCRIPTION': 'LOAD_INCREMENT',
                    'GROUP': '',
                    'HEADER': 'Load_Increment',
                    'TYPE': 'DEFAULT'},
 'LOAD_RAMP': {'DESCRIPTION': 'LOAD_RAMP',
               'GROUP': '',
               'HEADER': 'Load_Ramp',
               'TYPE': 'DEFAULT'},
 'MAX_ADJ_DENSITY': {'DESCRIPTION': 'Maximum residual of the adjoint density.',
                     'GROUP': 'MAX_RES',
                     'HEADER': 'max[A_Rho]',
                     'TYPE': 'RESIDUAL'},
 'MAX_ADJ_DISSIPATION': {'DESCRIPTION': 'Maximum residual of the adjoint '
                                        'dissipation.',
                         'GROUP': 'MAX_RES',
                         'HEADER': 'max[A_w]',
                         'TYPE': 'RESIDUAL'},
 'MAX_ADJ_ENERGY': {'DESCRIPTION': 'Maximum residual of the adjoint energy.',
                    'GROUP': 'MAX_RES',
                    'HEADER': 'max[A_E]',
                    'TYPE': 'RESIDUAL'},
 'MAX_ADJ_HEAT': {'DESCRIPTION': 'Maximum residual of the temperature.',
                  'GROUP': 'MAX_RES',
                  'HEADER': 'max[A_T]',
                  'TYPE': 'RESIDUAL'},
 'MAX_ADJ_MOMENTUM-X': {'DESCRIPTION': 'Maximum residual of the adjoint '
                                       'momentum x-component',
                        'GROUP': 'MAX_RES',
                        'HEADER': 'max[A_RhoU]',
                        'TYPE': 'RESIDUAL'},
 'MAX_ADJ_MOMENTUM-Y': {'DESCRIPTION': 'Maximum residual of the adjoint '
                                       'momentum y-component',
                        'GROUP': 'MAX_RES',
                        'HEADER': 'max[A_RhoV]',
                        'TYPE': 'RESIDUAL'},
 'MAX_ADJ_MOMENTUM-Z': {'DESCRIPTION': 'Maximum residual of the adjoint '
                                       'momentum z-component',
                        'GROUP': 'MAX_RES',
                        'HEADER': 'max[A_RhoW]',
                        'TYPE': 'RESIDUAL'},
 'MAX_ADJ_NU_TILDE': {'DESCRIPTION': 'Maximum residual of the adjoint nu '
                                     'tilde.',
                      'GROUP': 'MAX_RES',
                      'HEADER': 'max[A_nu]',
                      'TYPE': 'RESIDUAL'},
 'MAX_ADJ_PRESSURE': {'DESCRIPTION': 'Maximum residual of the adjoint '
                                     'Pressure.',
                      'GROUP': 'MAX_RES',
                      'HEADER': 'max[A_Rho]',
                      'TYPE': 'RESIDUAL'},
 'MAX_ADJ_TEMPERATURE': {'DESCRIPTION': 'BGS residual of the adjoint '
                                        'temperature.',
                         'GROUP': 'BGS_RES',
                         'HEADER': 'max[A_T]',
                         'TYPE': 'RESIDUAL'},
 'MAX_ADJ_TKE': {'DESCRIPTION': 'Maximum residual of the adjoint kinetic '
                                'energy.',
                 'GROUP': 'MAX_RES',
                 'HEADER': 'max[A_k]',
                 'TYPE': 'RESIDUAL'},
 'MAX_ADJ_VELOCITY-X': {'DESCRIPTION': 'Maximum residual of the adjoint '
                                       'Velocity x-component',
                        'GROUP': 'MAX_RES',
                        'HEADER': 'max[A_RhoU]',
                        'TYPE': 'RESIDUAL'},
 'MAX_ADJ_VELOCITY-Y': {'DESCRIPTION': 'Maximum residual of the adjoint '
                                       'Velocity y-component',
                        'GROUP': 'MAX_RES',
                        'HEADER': 'max[A_RhoV]',
                        'TYPE': 'RESIDUAL'},
 'MAX_ADJ_VELOCITY-Z': {'DESCRIPTION': 'Maximum residual of the adjoint '
                                       'Velocity z-component',
                        'GROUP': 'MAX_RES',
                        'HEADER': 'max[A_RhoW]',
                        'TYPE': 'RESIDUAL'},
 'MAX_DENSITY': {'DESCRIPTION': 'Maximum square residual of the density.',
                 'GROUP': 'MAX_RES',
                 'HEADER': 'max[Rho]',
                 'TYPE': 'RESIDUAL'},
 'MAX_DISSIPATION': {'DESCRIPTION': 'Maximum residual of dissipation (SST '
                                    'model).',
                     'GROUP': 'MAX_RES',
                     'HEADER': 'max[w]',
                     'TYPE': 'RESIDUAL'},
 'MAX_ENERGY': {'DESCRIPTION': 'Maximum residual of the energy.',
                'GROUP': 'MAX_RES',
                'HEADER': 'max[RhoE]',
                'TYPE': 'RESIDUAL'},
 'MAX_MOMENTUM-X': {'DESCRIPTION': 'Maximum square residual of the momentum '
                                   'x-component.',
                    'GROUP': 'MAX_RES',
                    'HEADER': 'max[RhoU]',
                    'TYPE': 'RESIDUAL'},
 'MAX_MOMENTUM-Y': {'DESCRIPTION': 'Maximum square residual of the momentum '
                                   'y-component.',
                    'GROUP': 'MAX_RES',
                    'HEADER': 'max[RhoV]',
                    'TYPE': 'RESIDUAL'},
 'MAX_NU_TILDE': {'DESCRIPTION': 'Maximum residual of nu tilde (SA model).',
                  'GROUP': 'MAX_RES',
                  'HEADER': 'max[nu]',
                  'TYPE': 'RESIDUAL'},
 'MAX_PRESSURE': {'DESCRIPTION': 'Maximum residual of the pressure.',
                  'GROUP': 'MAX_RES',
                  'HEADER': 'max[P]',
                  'TYPE': 'RESIDUAL'},
 'MAX_TEMPERATURE': {'DESCRIPTION': 'Maximum residual of the temperature',
                     'GROUP': 'MAX_RES',
                     'HEADER': 'max[T]',
                     'TYPE': 'RESIDUAL'},
 'MAX_TKE': {'DESCRIPTION': 'Maximum residual of kinetic energy (SST model).',
             'GROUP': 'MAX_RES',
             'HEADER': 'max[k]',
             'TYPE': 'RESIDUAL'},
 'MAX_VELOCITY-X': {'DESCRIPTION': 'Maximum residual of the velocity '
                                   'x-component.',
                    'GROUP': 'MAX_RES',
                    'HEADER': 'max[U]',
                    'TYPE': 'RESIDUAL'},
 'MAX_VELOCITY-Y': {'DESCRIPTION': 'Maximum residual of the velocity '
                                   'y-component.',
                    'GROUP': 'MAX_RES',
                    'HEADER': 'max[V]',
                    'TYPE': 'RESIDUAL'},
 'MAX_VELOCITY-Z': {'DESCRIPTION': 'Maximum residual of the velocity '
                                   'z-component.',
                    'GROUP': 'MAX_RES',
                    'HEADER': 'max[W]',
                    'TYPE': 'RESIDUAL'},
 'MERIT': {'DESCRIPTION': 'Merit',
           'GROUP': 'ROTATING_FRAME',
           'HEADER': 'CMerit',
           'TYPE': 'COEFFICIENT'},
 'MOMENTUM_DISTORTION': {'DESCRIPTION': 'Total momentum distortion on all '
                                        'markers set in MARKER_ANALYZE',
                         'GROUP': 'FLOW_COEFF',
                         'HEADER': 'Momentum_Distortion',
                         'TYPE': 'COEFFICIENT'},
 'MOMENT_X': {'DESCRIPTION': 'Total momentum x-component on all surfaces set '
                             'with MARKER_MONITORING',
              'GROUP': 'AERO_COEFF',
              'HEADER': 'CMx',
              'TYPE': 'COEFFICIENT'},
 'MOMENT_Y': {'DESCRIPTION': 'Total momentum y-component on all surfaces set '
                             'with MARKER_MONITORING',
              'GROUP': 'AERO_COEFF',
              'HEADER': 'CMy',
              'TYPE': 'COEFFICIENT'},
 'MOMENT_Z': {'DESCRIPTION': 'Total momentum z-component on all surfaces set '
                             'with MARKER_MONITORING',
              'GROUP': 'AERO_COEFF',
              'HEADER': 'CMz',
              'TYPE': 'COEFFICIENT'},
 'NEARFIELD_OF': {'DESCRIPTION': 'Nearfield obj. function',
                  'GROUP': 'EQUIVALENT_AREA',
                  'HEADER': 'CNearFieldOF',
                  'TYPE': 'COEFFICIENT'},
 'PRESSURE_DROP': {'DESCRIPTION': 'Total pressure drop on all markers set in '
                                  'MARKER_ANALYZE',
                   'GROUP': 'FLOW_COEFF',
                   'HEADER': 'Pressure_Drop',
                   'TYPE': 'COEFFICIENT'},
 'RADIAL_DISTORTION': {'DESCRIPTION': 'Radial distortion',
                       'GROUP': 'ENGINE_OUTPUT',
                       'HEADER': 'Radial_Distortion',
                       'TYPE': 'COEFFICIENT'},
 'RMS_ADJ_DENSITY': {'DESCRIPTION': 'Root-mean square residual of the adjoint '
                                    'density.',
                     'GROUP': 'RMS_RES',
                     'HEADER': 'rms[A_Rho]',
                     'TYPE': 'RESIDUAL'},
 'RMS_ADJ_DISSIPATION': {'DESCRIPTION': 'Root-mean square residual of the '
                                        'adjoint dissipation.',
                         'GROUP': 'RMS_RES',
                         'HEADER': 'rms[A_w]',
                         'TYPE': 'RESIDUAL'},
 'RMS_ADJ_ENERGY': {'DESCRIPTION': 'Root-mean square residual of the adjoint '
                                   'energy.',
                    'GROUP': 'RMS_RES',
                    'HEADER': 'rms[A_E]',
                    'TYPE': 'RESIDUAL'},
 'RMS_ADJ_HEAT': {'DESCRIPTION': 'Root-mean square residual of the adjoint '
                                 'temperature.',
                  'GROUP': 'RMS_RES',
                  'HEADER': 'rms[A_T]',
                  'TYPE': 'RESIDUAL'},
 'RMS_ADJ_MOMENTUM-X': {'DESCRIPTION': 'Root-mean square residual of the '
                                       'adjoint momentum x-component.',
                        'GROUP': 'RMS_RES',
                        'HEADER': 'rms[A_RhoU]',
                        'TYPE': 'RESIDUAL'},
 'RMS_ADJ_MOMENTUM-Y': {'DESCRIPTION': 'Root-mean square residual of the '
                                       'adjoint momentum y-component.',
                        'GROUP': 'RMS_RES',
                        'HEADER': 'rms[A_RhoV]',
                        'TYPE': 'RESIDUAL'},
 'RMS_ADJ_MOMENTUM-Z': {'DESCRIPTION': 'Root-mean square residual of the '
                                       'adjoint momentum z-component.',
                        'GROUP': 'RMS_RES',
                        'HEADER': 'rms[A_RhoW]',
                        'TYPE': 'RESIDUAL'},
 'RMS_ADJ_NU_TILDE': {'DESCRIPTION': 'Root-mean square residual of the adjoint '
                                     'nu tilde.',
                      'GROUP': 'RMS_RES',
                      'HEADER': 'rms[A_nu]',
                      'TYPE': 'RESIDUAL'},
 'RMS_ADJ_PRESSURE': {'DESCRIPTION': 'Root-mean square residual of the adjoint '
                                     'Pressure.',
                      'GROUP': 'RMS_RES',
                      'HEADER': 'rms[A_P]',
                      'TYPE': 'RESIDUAL'},
 'RMS_ADJ_TEMPERATURE': {'DESCRIPTION': 'Root-mean square residual of the '
                                        'adjoint temperature.',
                         'GROUP': 'RMS_RES',
                         'HEADER': 'rms[A_T]',
                         'TYPE': 'RESIDUAL'},
 'RMS_ADJ_TKE': {'DESCRIPTION': 'Root-mean square residual of the adjoint '
                                'kinetic energy.',
                 'GROUP': 'RMS_RES',
                 'HEADER': 'rms[A_k]',
                 'TYPE': 'RESIDUAL'},
 'RMS_ADJ_VELOCITY-X': {'DESCRIPTION': 'Root-mean square residual of the '
                                       'adjoint Velocity x-component.',
                        'GROUP': 'RMS_RES',
                        'HEADER': 'rms[A_U]',
                        'TYPE': 'RESIDUAL'},
 'RMS_ADJ_VELOCITY-Y': {'DESCRIPTION': 'Root-mean square residual of the '
                                       'adjoint Velocity y-component.',
                        'GROUP': 'RMS_RES',
                        'HEADER': 'rms[A_V]',
                        'TYPE': 'RESIDUAL'},
 'RMS_ADJ_VELOCITY-Z': {'DESCRIPTION': 'Root-mean square residual of the '
                                       'adjoint Velocity z-component.',
                        'GROUP': 'RMS_RES',
                        'HEADER': 'rms[A_W]',
                        'TYPE': 'RESIDUAL'},
 'RMS_DENSITY': {'DESCRIPTION': 'Root-mean square residual of the density.',
                 'GROUP': 'RMS_RES',
                 'HEADER': 'rms[Rho]',
                 'TYPE': 'RESIDUAL'},
 'RMS_DISP_X': {'DESCRIPTION': '',
                'GROUP': 'RMS_RES',
                'HEADER': 'rms[DispX]',
                'TYPE': 'RESIDUAL'},
 'RMS_DISP_Y': {'DESCRIPTION': '',
                'GROUP': 'RMS_RES',
                'HEADER': 'rms[DispY]',
                'TYPE': 'RESIDUAL'},
 'RMS_DISP_Z': {'DESCRIPTION': '',
                'GROUP': 'RMS_RES',
                'HEADER': 'rms[DispZ]',
                'TYPE': 'RESIDUAL'},
 'RMS_DISSIPATION': {'DESCRIPTION': 'Root-mean square residual of dissipation '
                                    '(SST model).',
                     'GROUP': 'RMS_RES',
                     'HEADER': 'rms[w]',
                     'TYPE': 'RESIDUAL'},
 'RMS_ENERGY': {'DESCRIPTION': 'Root-mean square residual of the energy.',
                'GROUP': 'RMS_RES',
                'HEADER': 'rms[RhoE]',
                'TYPE': 'RESIDUAL'},
 'RMS_ETOL': {'DESCRIPTION': '',
              'GROUP': 'RMS_RES',
              'HEADER': 'rms[E]',
              'TYPE': 'RESIDUAL'},
 'RMS_MOMENTUM-X': {'DESCRIPTION': 'Root-mean square residual of the momentum '
                                   'x-component.',
                    'GROUP': 'RMS_RES',
                    'HEADER': 'rms[RhoU]',
                    'TYPE': 'RESIDUAL'},
 'RMS_MOMENTUM-Y': {'DESCRIPTION': 'Root-mean square residual of the momentum '
                                   'y-component.',
                    'GROUP': 'RMS_RES',
                    'HEADER': 'rms[RhoV]',
                    'TYPE': 'RESIDUAL'},
 'RMS_NU_TILDE': {'DESCRIPTION': 'Root-mean square residual of nu tilde (SA '
                                 'model).',
                  'GROUP': 'RMS_RES',
                  'HEADER': 'rms[nu]',
                  'TYPE': 'RESIDUAL'},
 'RMS_PRESSURE': {'DESCRIPTION': 'Root-mean square residual of the pressure.',
                  'GROUP': 'RMS_RES',
                  'HEADER': 'rms[P]',
                  'TYPE': 'RESIDUAL'},
 'RMS_RTOL': {'DESCRIPTION': '',
              'GROUP': 'RMS_RES',
              'HEADER': 'rms[R]',
              'TYPE': 'RESIDUAL'},
 'RMS_TEMPERATURE': {'DESCRIPTION': 'Root mean square residual of the '
                                    'temperature',
                     'GROUP': 'RMS_RES',
                     'HEADER': 'rms[T]',
                     'TYPE': 'RESIDUAL'},
 'RMS_TKE': {'DESCRIPTION': 'Root-mean square residual of kinetic energy (SST '
                            'model).',
             'GROUP': 'RMS_RES',
             'HEADER': 'rms[k]',
             'TYPE': 'RESIDUAL'},
 'RMS_UTOL': {'DESCRIPTION': '',
              'GROUP': 'RMS_RES',
              'HEADER': 'rms[U]',
              'TYPE': 'RESIDUAL'},
 'RMS_VELOCITY-X': {'DESCRIPTION': 'Root-mean square residual of the velocity '
                                   'x-component.',
                    'GROUP': 'RMS_RES',
                    'HEADER': 'rms[U]',
                    'TYPE': 'RESIDUAL'},
 'RMS_VELOCITY-Y': {'DESCRIPTION': 'Root-mean square residual of the velocity '
                                   'y-component.',
                    'GROUP': 'RMS_RES',
                    'HEADER': 'rms[V]',
                    'TYPE': 'RESIDUAL'},
 'SECONDARY_OVER_UNIFORMITY': {'DESCRIPTION': 'Total secondary over uniformity '
                                              'on all markers set in '
                                              'MARKER_ANALYZE',
                               'GROUP': 'FLOW_COEFF',
                               'HEADER': 'Secondary_Over_Uniformity',
                               'TYPE': 'COEFFICIENT'},
 'SECONDARY_STRENGTH': {'DESCRIPTION': 'Total secondary strength on all '
                                       'markers set in MARKER_ANALYZE',
                        'GROUP': 'FLOW_COEFF',
                        'HEADER': 'Secondary_Strength',
                        'TYPE': 'COEFFICIENT'},
 'SENS_AOA': {'DESCRIPTION': 'Sensitivity of the objective function with '
                             'respect to the angle of attack (only for '
                             'compressible solver).',
              'GROUP': 'SENSITIVITY',
              'HEADER': 'Sens_AoA',
              'TYPE': 'COEFFICIENT'},
 'SENS_E': {'DESCRIPTION': '',
            'GROUP': 'SENSITIVITY',
            'HEADER': 'Sens[E]',
            'TYPE': 'DEFAULT'},
 'SENS_GEO': {'DESCRIPTION': 'Sum of the geometrical sensitivities on all '
                             'markers set in MARKER_MONITORING.',
              'GROUP': 'SENSITIVITY',
              'HEADER': 'Sens_Geo',
              'TYPE': 'COEFFICIENT'},
 'SENS_MACH': {'DESCRIPTION': 'Sensitivity of the objective function with '
                              'respect to the Mach number (only of '
                              'compressible solver).',
               'GROUP': 'SENSITIVITY',
               'HEADER': 'Sens_Mach',
               'TYPE': 'COEFFICIENT'},
 'SENS_NU': {'DESCRIPTION': '',
             'GROUP': 'SENSITIVITY',
             'HEADER': 'Sens[Nu]',
             'TYPE': 'DEFAULT'},
 'SENS_PRESS': {'DESCRIPTION': 'Sensitivity of the objective function with '
                               'respect to the far-field pressure.',
                'GROUP': 'SENSITIVITY',
                'HEADER': 'Sens_Press',
                'TYPE': 'COEFFICIENT'},
 'SENS_PRESS_OUT': {'DESCRIPTION': 'Sensitivity of the objective function with '
                                   'respect to the outlet pressure.',
                    'GROUP': 'SENSITIVITY',
                    'HEADER': 'Sens_Pout',
                    'TYPE': 'COEFFICIENT'},
 'SENS_TEMP': {'DESCRIPTION': 'Sensitivity of the objective function with '
                              'respect to the far-field temperature.',
               'GROUP': 'SENSITIVITY',
               'HEADER': 'Sens_Temp',
               'TYPE': 'COEFFICIENT'},
 'SENS_VEL_IN': {'DESCRIPTION': 'Sensitivity of the objective function with '
                                'respect to the inlet velocity.',
                 'GROUP': 'SENSITIVITY',
                 'HEADER': 'Sens_Vin',
                 'TYPE': 'COEFFICIENT'},
 'SIDEFORCE': {'DESCRIPTION': 'Total sideforce coefficient on all surfaces set '
                              'with MARKER_MONITORING',
               'GROUP': 'AERO_COEFF',
               'HEADER': 'CSF',
               'TYPE': 'COEFFICIENT'},
 'SOLIDCDRAG': {'DESCRIPTION': 'Solid CD drag',
                'GROUP': 'ENGINE_OUTPUT',
                'HEADER': 'SolidCDrag',
                'TYPE': 'COEFFICIENT'},
 'TEMPERATURE': {'DESCRIPTION': 'Total avg. temperature on all surfaces set '
                                'with MARKER_MONITORING.',
                 'GROUP': 'HEAT',
                 'HEADER': 'Temp',
                 'TYPE': 'COEFFICIENT'},
 'UNIFORMITY': {'DESCRIPTION': 'Total flow uniformity on all markers set in '
                               'MARKER_ANALYZE',
                'GROUP': 'FLOW_COEFF',
                'HEADER': 'Uniformity',
                'TYPE': 'COEFFICIENT'},
 'VMS': {'DESCRIPTION': 'VMS',
         'GROUP': '',
         'HEADER': 'VonMises',
         'TYPE': 'DEFAULT'}}
