# -*- cmake -*-
# - Find JSONCPP
#
# yue.nicholas@gmail.com
#

FIND_PACKAGE ( PackageHandleStandardArgs )

FIND_PATH( JSONCPP_LOCATION include/json/json.h 
  $ENV{JSONCPP_ROOT}
  NO_DEFAULT_PATH
  NO_SYSTEM_ENVIRONMENT_PATH
  )

MESSAGE ( "JSONCPP_LOCATION = ${JSONCPP_LOCATION}/include" )

FIND_PACKAGE_HANDLE_STANDARD_ARGS ( Jsoncpp
  REQUIRED_VARS JSONCPP_LOCATION
  )

IF ( JSONCPP_FOUND )
  SET( JSONCPP_INCLUDE_DIR "${JSONCPP_LOCATION}/include" CACHE STRING "JSONCPP include path")
  FILE ( GLOB JSON_LIBRARY "${JSONCPP_LOCATION}/lib/*.a")
  SET ( JSONCPP_json_LIBRARY ${JSON_LIBRARY} CACHE STRING "JSONCPP library")
ENDIF ()
