name: Code Style
on:
  pull_request:
    paths:
      - "**.[ch]pp"
      - "**.[ch]"
      - "**.cfg"
      - "**.py"

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
         python-version: '3.10'
         check-latest: true
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run checks
        run: pre-commit run -a -v
      - name: Git status
        if: always()
        run: git status
      - name: Full diff
        if: always()
        run: git diff
